MIN_BUTTON_HEIGHT = 10
MIN_BUTTON_WIDTH = 10

DEFAULT_TILE_WIDTH = 100
DEFAULT_TILE_HEIGHT = 100

REMOTE_BUTTONS = [
    "HOME",
    "POWER",
    "SELECT",
    "NAV_UP",
    "NAV_RIGHT",
    "NAV_DOWN",
    "NAV_LEFT",
    "MENU",
    "RETURN",
    "VOL_UP",
    "VOL_DOWN",
    "MIC",
]